product:
  category:
  - books
  - ebooks
  - audiobooks
  - giftcards
  list:
  - id: 1
    category: books
    title: Роман Михайлов «Изнанка крысы»
    description: "Вы входите в текст-лабиринт. Каждый его поворот — проникновение в свой слой языка восточный мистицизм, криптоанархия, шифропанк, метафизическое подполье, шизотерическая лингвистика, постструктурализм. Стены этого лабиринта сложены из липкого ужаса, просачивающегося через трещины реальности. Вместо выхода — интимная исповедь, написанная ритмом галлюцинаторных приступов, нанизанная на решётчатые структуры, вывернутая к вам живой, беззащитной изнанкой существования. Для преподавателей вузов и охотников на птиц-оборотней."
    shortDescription: "Вы входите в текст-лабиринт. Каждый его поворот — проникновение в свой слой языка восточный мистицизм, криптоанархия, шифропанк, метафизическое подполье"
    additionalInfo: "СПб.: Издательство книжного магазина Все Свободны, 2018. — 240 с., илл. Обложка с клапанами."
    badge: Popular
    price: 120.00
    priceOld: 140.00
    stars: 5
    images:
    - https://i.postimg.cc/15GtqR5Q/67ec23_085cb365769d466596f2210fbbe71aa5_mv2.jpg
    - https://i.postimg.cc/02PvhYxT/67ec23_bcf9f8f3b37741cfbb0a259e060aad7a_mv2_d_2200_1800_s_2.jpg
  - id: 2
    category: books
    title: журнал «Фрейдово подполье» №2
    description: "1. Kant avec Sade Комментарии к переводу текста Жака Лакана «Кант с де Садом» Филипп Соллерс «Письмо Сада» Интервью с переводчиком Лакана Александром Черноглазовым 2. Politika Хорхе Алеман «Различие между субъектом и субъективностью» Хорхе Алеман «Неолиберальные горизонты субъективности» Маурисио Рухелес «Хорхе Алеман и Эрнесто Лакло: Гегемония и дискурс капиталиста» Александр Бронников «К логике сексуации: от нехватки знаний в теории Брауэра к кастрации в теории Остина»"
    shortDescription: "1. Kant avec Sade Комментарии к переводу текста Жака Лакана «Кант с де Садом» Филипп Соллерс «Письмо Сада» Интервью с переводчиком Лакана Александром Черноглазовым"
    additionalInfo: "Фрейдово подполье, 2018 - 68 с. Обложка"
    badge: Popular
    price: 100.00
    priceOld: 120.00
    stars: 4
    images:
    - https://i.postimg.cc/65YkSFMZ/67ec23_f148d4f1e62b48a38529954b5ec95d53_mv2.jpg
    - https://i.postimg.cc/65YkSFMZ/67ec23_f148d4f1e62b48a38529954b5ec95d53_mv2.jpg
  - id: 3
    category: ebooks
    title: Василина Орлова «Антрополгия повседневности»
    description: "«Название новой книги Василины Орловой может кого-то испугать. В общественном представлении антропология, это что-то связанное с черепами. Но не стоит пугаться – «Антропология повседневности» произведение, полное колоритной жизни, вкусной речи. К сожалению, жизни, которая стремительно изменяется, речи, становящейся всё преснее. Всё меньше заповедных уголков в Сибири – а основная часть книги посвящена ей, – где существует особенная речь, свои традиции и своя эстетика. Василина Орлова торопится всё это запечатлеть. В последние годы автор в основном живет далеко от России, но ее приезды на родину теперь сопровождаются экспедициями в такие уголки, где не бывало абсолютное большинство россиян. И вообще, как отмечает сама Орлова, «я никогда ранее не сделала столь решительного шага навстречу России, как только покинув страну»."
    shortDescription: "«Название новой книги Василины Орловой может кого-то испугать. В общественном представлении антропология, это что-то связанное с черепами. Но не стоит пугаться – «Антропология повседневности» произведение, полное колоритной жизни, вкусной речи."
    additionalInfo: "М.: Ноократия, 2018. - 241 с."
    badge: ""
    price: 70.00
    priceOld: 70.00
    stars: 3
    images:
    - https://i.postimg.cc/t4sMcJZ0/67ec23_89691cbf5e324e388f1f867913c7bc19_mv2.jpg
    - https://i.postimg.cc/t4sMcJZ0/67ec23_89691cbf5e324e388f1f867913c7bc19_mv2.jpg
  - id: 4
    category: ebooks
    title: Бенедикт Сарнов «Сталин и писатели. Книга первая»
    description: "«Мне показалось необычайно заманчивым, отталкиваясь от документов и опираясь на них, расширяя границы документа, внимательно и по возможности подробно рассмотреть “взаимоотношения” со Сталиным каждого из тех писателей, на чью судьбу наложило свою печать чугунное сталинское слово». (Бенедикт Сарнов.) В первый том фундаментальной литературоведческой эпопеи «Сталин и писатели» вошли шесть глав: «Сталин и Горький», «Сталин и Маяковский», «Сталин и Пастернак», «Сталин и Мандельштам», «Сталин и Демьян Бедный», «Сталин и Эренбург»."
    shortDescription: "«Мне показалось необычайно заманчивым, отталкиваясь от документов и опираясь на них, расширяя границы документа, внимательно и по возможности подробно рассмотреть"
    additionalInfo: "М.: КоЛибри, 2018 - 704 с. Переплет"
    badge: -50%
    price: 40.00
    priceOld: 80.00
    stars: 2
    images:
    - https://i.postimg.cc/SNM9tpST/67ec23_21f34a7af02e499582c1aa58b6ec840c_mv2.jpg
    - https://i.postimg.cc/SNM9tpST/67ec23_21f34a7af02e499582c1aa58b6ec840c_mv2.jpg
  - id: 5
    category: audiobooks
    title: Татьяна Москвина «Топ-топ хронотоп»
    description: "Татьяна Москвина – известный писатель и драматург, автор романов «Смерть это все мужчины», «Она что-то знала», «Позор и чистота» и около полудюжины пьес. Вместе с тем Москвина – один из ведущих российских театральных критиков и театроведов, бесспорный авторитет в области классического и современного театра. В этой книге Москвина в своей неподражаемой - вместе и едкой, и доверительной - манере делится с читателем своими наблюдениями и рассуждениями обо всем на свете, от книг и спектаклей до явлений повседневности. «Топ-топ хронотоп» похожа на разговор с умным, внимательным, доброжелательным, но во многих вещах принципиальным собеседником."
    shortDescription: "Татьяна Москвина – известный писатель и драматург, автор романов «Смерть это все мужчины», «Она что-то знала», «Позор и чистота» и около полудюжины пьес. Вместе с тем Москвина – один"
    additionalInfo: "М.: Флюид ФриФлай, 2018 - 352 с. Обложка"
    badge: -30%
    price: 50.00
    priceOld: 80.00
    stars: 1
    images:
    - https://i.postimg.cc/nh1G0tT8/67ec23_e5fd9145ec21400289e1573e157815b4_mv2.jpg
    - https://i.postimg.cc/nh1G0tT8/67ec23_e5fd9145ec21400289e1573e157815b4_mv2.jpg
  - id: 6
    category: audiobooks
    title: Пол Кеннеди «Взлеты и падения великих держав»
    description: "Книга известного британского ученого Пола Кеннеди рассматривает историю непрерывных смещений мировых центров власти на протяжении последних пятисот лет — от эпохи зарождения в Европе крупных монархий и зачатков колониальных империй до начала XXI в. Подчеркивая взаимосвязь экономики, научно-технических инноваций и способности государственной политики эффективно задействовать свои ресурсы в мирное время и в состоянии войны, автор выводит закономерности, позволяющие тому или иному государству в определенный момент истории получать лидерство на мировой арене, которое в результате нарушения равновесия между военным и экономическим потенциалом легко переходит к новой мировой державе. Впервые книга была опубликована 1987 г., и последняя глава в ней звучала как прогноз относительно возможного баланса сил в мире к началу XXI в."
    shortDescription: "Книга известного британского ученого Пола Кеннеди рассматривает историю непрерывных смещений мировых центров власти на протяжении последних пятисот лет — от эпохи"
    additionalInfo: "Екатеринбург: Гонзо, 2018 - 848 с. (12 карт, 49 табл., библиография) Переплет"
    badge: -50%
    price: 40.00
    priceOld: 80.00
    stars: 4
    images:
    - https://i.postimg.cc/3NpgpMWc/67ec23_56e99a968856465abfdc84c2775ac91e_mv2.jpg
    - https://i.postimg.cc/3NpgpMWc/67ec23_56e99a968856465abfdc84c2775ac91e_mv2.jpg
  - id: 7
    category: giftcards
    title: Подарочный сертификат
    description: "Подарочный сертификат"
    shortDescription: "Подарочный сертификат"
    additionalInfo: ""
    badge: Popular
    price: 1.00
    priceOld: 0
    stars: 5
    images:
    - https://i.postimg.cc/fTsN9xrH/Gift-_Coupon.jpg
  - id: 8
    category: audiobooks
    title: Максим Жук «Путь к Замку, или курс лекций о Франце Кафке»
    description: "«Моя книга — это не академический текст, написанный сложным научным языком, но и не поверхностная брошюра в жанре «Кафка за 5 минут». Я хочу рассказать вам доступным  языком о своем понимании творчества Кафки, показать исторический и культурный контекст, который сформировал писателя, очертить основные контуры его художественного мира, объяснить основные варианты интерпретаций его ключевых произведений: новеллы «Превращение» и романов «Америка», «Процесс», «Замок». Отдельная часть посвящена восприятию наследия Кафки в русской культуре и судьбе публикации его произведений в СССР. В книге впервые на русском языке опубликована новелла Карла Бранда «Обратное превращение Грегора Замзы» (1916) — продолжение кафкианской новеллы «Превращение» (1912)».
— Максим Жук
  Максим Жук — кандидат филологических наук, доцент кафедры романо-германской филологии Дальневосточного федерального университета (г. Владивосток). Преподает историю зарубежной литературы с  2004 года."
    shortDescription: "«Моя книга — это не академический текст, написанный сложным научным языком, но и не поверхностная брошюра в жанре «Кафка за 5 минут»."
    additionalInfo: "Ridero, 2018. – 220 с. Обложка"
    badge: -10%
    price: 270.00
    priceOld: 300.00
    stars: 4
    images:
    - https://i.postimg.cc/6QFs5RZf/67ec23_7173abeef4ee4aaf938b9cacfa6f1a49_mv2.jpg
  - id: 9
    category: books
    title: Россия—Грузия после империи - сборник статей
    description: "В сборник вошли научные, литературные, публицистические материалы и интервью культурологов и литературоведов из разных стран (Германия, Грузия, Польша, Россия, США и др.), а также наблюдателей постсоветских трансформаций русско-грузинских отношений. Главная задача исследований — выделить в рамках междисциплинарного и международного диалога актуальные темы и ракурсы моделирования новой реальности этого литературно-культурного поля. Именно литература предоставила полезный материал, позволивший заглянуть за кулисы геополитических нарративов, так как политически значимые мыслительные категории являются неразрывно связанными как с литературными образами России и Грузии, так и с русско-грузинским мифом. Если в советскую эпоху этот миф способствовал почти ритуальному изучению истории взаимоотношений двух народов, то начиная со второй половины 1980-х годов именно он стал своего рода фундаментом для политического, военного, а также, как тогда казалось, и культурного размежевания некогда «братских республик»."
    shortDescription: "В сборник вошли научные, литературные, публицистические материалы и интервью культурологов и литературоведов из разных стран (Германия, Грузия, Польша, Россия, США и др.)"
    additionalInfo: "М.: Новое литературное обозрение, 2018. - 400 с.Переплет"
    badge: -10%
    price: 450.00
    priceOld: 500.00
    stars: 4
    images:
    - https://i.postimg.cc/QxmRKv5t/67ec23_669234124aed42228f347f8306399bfc_mv2.jpg
  - id: 10
    category: books
    title: Журнал «Искусство», №1 2018 «Британия»
    description: "Новый номер журнала посвящён современному искусству Великобритании. Сейчас в условиях Брекзита эта страна оказалась вынуждена выбирать между национальным и международным, и значит заново определять своё место в мире и выяснять отношения с собственной историей. Мы же рассказываем, как это происходит на примерах лучшего искусства Соединённого королевства.
                    В номере есть рассказ о том, как эстетика прерафаэлитов спасает сквоттеров из Ист-Энда; телерепортаж о последней битве шотландских горцев; перформанс Джереми Деллера, посвященный Битве на Сомме, где нет никакой битвы; рассказ об арт-резиденции в Озерном краю, живущей по заветам Джона Рёскина. Все эти примеры обнажают пласты национальной культуры, не всегда очевидные для иностранца, попавшего в прославленный музей или в галерею с лучшим современным искусством планеты. Однако важно и то, что такие художественные стратегии работы с местным прошлым и местными сообществами — и есть самые актуальные сегодня в международном арт-пространстве."
    shortDescription: "Новый номер журнала посвящён современному искусству Великобритании."
    additionalInfo: "М.: журнал Искусство, 2018 - 112 с.Обложка"
    badge: -10%
    price: 540.00
    priceOld: 600.00
    stars: 4
    images:
    - https://i.postimg.cc/KY6VybX9/67ec23_f645289a54a1411f908847d39b0246ab_mv2_d_1851_2384_s_2.jpg
  - id: 11
    category: books
    title: «Слеза социализма. Дом забытых писателей»
    description: "В 1929–1931 годы в Ленинграде, на улице Рубинштейна, был построен дом-коммуна инженеров и писателей, почти сразу же прозванный «Слезой социализма» — в нем жили Ольга Берггольц, Ида Наппельбаум, Вольф Эрлих и другие литераторы, многие из которых сегодня незаслуженно забыты. Перед вами сборник их произведений, написанных в конце 1920-х — начале 1930-х и не печатавшихся (за редким исключением) с довоенных времен. Это книга о времени, когда «слезинцы» были молоды, а вера в светлое будущее еще не разбилась о большой террор, Великую Отечественную войну и страшную блокаду — о времени идеалистов, которое закончилось быстро и трагично."
    shortDescription: "Это книга о времени, когда «слезинцы» были молоды, а вера в светлое будущее еще не разбилась о большой террор, Великую Отечественную войну и страшную блокаду — о времени идеалистов, которое закончилось быстро и трагично."
    additionalInfo: "СПб.: Common place, 2018. - 446 с.Переплет"
    badge: -10%
    price: 450.00
    priceOld: 500.00
    stars: 5
    images:
    - https://i.postimg.cc/XvCHLPZ9/67ec23_da05d3d6078d456abb24d4b299f50e5e_mv2.jpg
  - id: 12
    category: books
    title: Герман Гессе «Магия книги»
    description: "Крупнейший немецкий прозаик XX века, лауреат Нобелевской премии по литературе, Герман Гессе известен в России прежде всего как автор «Сиддхартхи», «Степного волка», «Игры в бисер», рассказов и сказок.В этой книге собраны критические эссе классика о мировой литературе, о судьбах книг и духовных ценностей в ХХ веке. Они посвящены творчеству писателей и философов Германии, Австрии, Франции, Англии, России, а также Испании и Китая."
    shortDescription: "Крупнейший немецкий прозаик XX века, лауреат Нобелевской премии по литературе, Герман Гессе известен в России прежде всего как автор «Сиддхартхи», «Степного волка», «Игры в бисер», рассказов и сказок."
    additionalInfo: "СПб.: Лимбус Пресс, 2018 - 336 с.Переплет"
    badge: -10%
    price: 270.00
    priceOld: 300.00
    stars: 5
    images:
    - https://i.postimg.cc/660HMnQb/67ec23_8f034fb767f54204b3fb8ec1e110e17e_mv2.jpg